### ISSUE TITLE
Can't use it within angular 7 application

### ISSUE THREAD

**Issue by jesusmariocalleja** [icambron/twix.js#111]
I have installed `twix` and `@types/twix` and I imported with `import * as twix from 'twix';` but when I execute it I have the following error `ERROR TypeError: this._mutated is not a function`.

It's abled to find the library, but not to use it. Also I realized that the `toArray` function is not included within this version.

**Comment by icambron** [comment]
Sounds like an error in the types file. Those aren't maintained here, though, and I don't know my way around them, so I'm not sure how to help.
