### ISSUE TITLE
Interoperability with moment-range

### ISSUE THREAD

**Issue by strarsis** [icambron/twix.js#114]
Can a twix range converted to a moment-range and back?
The all-day range option of twix is very useful for me, but most of the code already uses moment-range.

**Comment by icambron** [comment]
Sure. To go from Twix to moment-range, just do

```js
var range = moment.range(twix.start(), twix.end());
```

To go the other way:

```js
var twix = range.start.twix(range.end);
```

(I haven't tested either of those, but I'm pretty sure they work)
