### ISSUE TITLE
Replace lang with introspection

### ISSUE THREAD

**Issue by icambron** [icambron/twix.js#42]
This seems obvious in retrospect, but instead of having settings for different languages (as we currently do for French), we should just parse the time formats in the Moment locales. For example...

```js
> moment.langData('fr')._longDateFormat.LL
'D MMMM YYYY'
> moment.langData('en')._longDateFormat.LL
'MMMM D YYYY'
```

...tells us what "slot" the month, date, and year go in. We can do something similar for 24 hour time vs AM/PM by checking LT. That gets me out managing locale files gets us a whole bunch of locales for free.

/cc @leo-naeka

**Comment by niemyjski** [comment]
I'm getting this warning as well:  Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.

Is there any updates on this?

**Comment by icambron** [comment]
@niemyjski @wizonesolutions Finally got around to releasing 0.6.0 - should fix that warning.

**Comment by niemyjski** [comment]
Awesome Thanks!

**Comment by icambron** [comment]
Not going to do this.
