### ISSUE TITLE
Locale Configurable Template Function

### ISSUE THREAD

**Issue by mgallag** [icambron/twix.js#49]
Allow for configurable locale specific template functions. This would allow for more complex range formatting of localized ranges than the current "firstDate - secondDate" format.

e.g. "del 6 - 8 de septiembre del 2014"

**Comment by icambron** [comment]
@mgallag I actually did a little bit of that in the language files - you'll see that if you include our language file that you get differently formatted output for French. It's sort of a crummy customization interface, though, and my experience helping with Moment.js makes me very much not want to maintain language files.

So I'm open to providing some extra templating options, but it's not obvious how to best set that up; I'm open to suggestions.

Final note is that I experimented a while ago in seeing if I could use the Moment's language specific formatting options to automatically determine the right template, but I haven't finished that yet (some of the progress is [here](https://github.com/icambron/twix.js/tree/localization-based-formatting)). I'm not sure if that's going to work out, though.
