### ISSUE TITLE
TypeError: Object <date> has no method 'twix'

### ISSUE THREAD

**Issue by nishantshreshth** [icambron/twix.js#60]
Running this basic example from doc:
```
var moment = require('moment');
require('twix');

var startTime = moment('2012 juillet', 'YYYY MMM', 'fr');
var endTime = moment('2012 August', 'YYYY MMM', 'en');
var range = startTime.twix(endTime);
console.log(range.simpleFormat());
```

results in:
```
var range = startTime.twix(endTime);
                      ^
TypeError: Object Sun Jul 01 2012 00:00:00 GMT+0530 has no method 'twix'
```

**Comment by icambron** [comment]
This is in Node?

**Comment by nishantshreshth** [comment]
Yes, it's node.

**Comment by nishantshreshth** [comment]
I think I had probably run into dependency/version-mismatch issue. Copying the source to a new directory and running npm install for both moment and twix made the error disappear. I think we can close this.

**Comment by icambron** [comment]
OK, good. It is certainly surprising to see, since Node is the best tested platform.
