### ISSUE TITLE
Incompatible with momentjs 2.10.0 in Meteor

### ISSUE THREAD

**Issue by cretep** [icambron/twix.js#61]
To reproduce:
```
meteor create test
cd test
meteor add momentjs:moment
meteor add momentjs:twix
meteor run
...
TypeError: Cannot set property '_twix' of undefined at Function.Twix._extend (packages/momentjs:twix/bin/twix.js:65:1)
...
```
I presume this is due to the ES6 refactoring.

Note that adding twix first will not cause an error, as Meteor will install momentjs 2.9 instead, due to that version being specified by twix.

The error is caused because twix's package.js specifies 2.9.0 **or higher**.

Therefore in the short term, I guess the easy fix is to edit https://github.com/icambron/twix.js/blob/develop/package.js#L16 to require version 2.9.0 exactly with an = sign. http://docs.meteor.com/#/full/pack_use

**Comment by icambron** [comment]
Hi @cretep I don't generally test it in Meteor, but since the problem actually effects all users of Moment, my fix probably works for you too. Can you try upgrading to 0.6.3 and seeing if your issues are resolved. (Caveat: https://github.com/icambron/twix.js/issues/62)

**Comment by cretep** [comment]
Fixed, thanks!
