### ISSUE TITLE
difference() returns wrong values when ranges are not created equally

### ISSUE THREAD

**Issue by jonagoldman** [icambron/twix.js#63]
So basically if I create two ranges using different parsing methods and try to get the difference() between them, the returned array is wrong.

For example:

```js
var range1 = moment(new Date(2015, 01, 01)).twix(new Date(2015, 01, 10));
var range2 = moment('02/01/2015', 'DD/MM/YYYY').twix('06/01/2015', 'DD/MM/YYYY');
var diff = range1.difference(range2);
````
this will return an array containing a wrong Twix object, in this case will just return 'range1'

**Comment by icambron** [comment]
Looks right to me:

```js
> range1.format()
'Feb 1, 12 AM - Feb 10, 12 AM'
> range2.format()
'Jan 2, 12 AM - Jan 6, 12 AM'
> diff[0].format()
'Feb 1, 12 AM - Feb 10, 12 AM'
```

Perhaps you're getting tripped up by the fact that JS months in the Date constructor are 1-indexed? If not, what do you expect ito return?

**Comment by jonagoldman** [comment]
Oops, my fault. You are right, Date constructors are 0-indexed... Thanks.
