### ISSUE TITLE
IIS doesn't like serving scripts out of the "bin" directory

### ISSUE THREAD

**Issue by davestaab** [icambron/twix.js#73]
Some servers like IIS don't server out of a folder named `bin` by default. 

Could we rename the bin directory to `dist`, `min` or some alternative?

**Comment by icambron** [comment]
I guess I don't quite understand - you can't just move the file?

I'd actually prefer something like `dist`, but I'm not super keen on breaking existing links.

**Comment by davestaab** [comment]
Yes, I'm currently moving the file to work around it.

Every time I do bower update I have to remember to move the files... kinda annoying. 

I know it's a long shot as basically everyone will have to update their script links if this happens. 

If you ever do a major release with breaking changes, I would consider adding this as it bypasses one more problem for IIS users.

**Comment by icambron** [comment]
OK. I'll leave this open to remind myself to do it when the time comes.

**Comment by bording** [comment]
:+1:  For making this change when possible!

**Comment by icambron** [comment]
I moved it to `build`. It's in the development branch right now and will be in the next release.

**Comment by icambron** [comment]
Actually, I'm going to change it to `dist` shortly, because `build` conflicts with my makefile `build` task, because Make is stupid.
