### ISSUE TITLE
Update configuration of webhook for autopublish.meteor.com

### ISSUE THREAD

**Issue by splendido** [icambron/twix.js#80]
Hi @icambron,
I've noticed that every new release triggers 2 publish operations on autopublish.meteor.com
I think the reason is the webhook was wrongly configured (not your fault....) to notify both new tags and new releases: since a new release also creates a new tag what we get is a double trigger and the second publish attempt usually fails with "Version already exists" error.

Could you please update the configuration to reflect what can be seen in [this screenshot](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks#releases)?
...you'll find the configuration page under _Settings -> Webhoks & Services_ ;-)

It's not a big problem though...

**Comment by icambron** [comment]
Hmm, I'm having a lot of trouble logging into autopublish. The oauth popup is blank...

**Comment by splendido** [comment]
Hmmm, really?!
Btw, the settings to be modified are those of your repo ;-)

**Comment by icambron** [comment]
It seems to be working now.

> Btw, the settings to be modified are those of your repo ;-)

Right, I was just curious about what was there.

I unchecked the "create" trigger, so now it's just "release".

**Comment by splendido** [comment]
:+1:
