### ISSUE TITLE
Include Twix version 0.9.0 on https://cdnjs.com

### ISSUE THREAD

**Issue by amtkmrsmn** [icambron/twix.js#84]
Please add current twix version on cdn. 

Thank you!!!

**Comment by icambron** [comment]
@amtkmrsmn I don't control that CDN. I recommend you write a pull request to update it in [their repository](https://github.com/cdnjs/cdnjs) -- it even looks like they now support auto-updating from the NPM package, so you'd only ever have to do it once.

**Comment by amtkmrsmn** [comment]
Thanks Issac



Thanks & Regards

Amit Kumar Suman

m +91 8587016330

**Comment by amtkmrsmn** [comment]
Thanks Issac

**Comment by icambron** [comment]
Actually, I bet that it doesn't work because this no longer has the right paths: https://github.com/cdnjs/cdnjs/pull/5039. There's no more `locale` and stuff is in `files/` instead of `bin/`

**Comment by icambron** [comment]
This seems to have been resolved: https://cdnjs.com/libraries/twix.js
