### ISSUE TITLE
Ability to split a date range by number

### ISSUE THREAD

**Issue by RemiAWE** [icambron/twix.js#87]
Hello, thank you for this excellent library.

Is there a way to split a dateRange in n parts ? Actually the `split()` function split only by a time or duration but it cannot split by number like `.split(5)`

**Comment by icambron** [comment]
There isn't a way to do that now. I'd accept a PR for a function called `divideEqually(numberOfParts)`

**Comment by icambron** [comment]
I added this in 03b055d and will release it soon. In the meantime, it turns out that it's really simple, so you can do it yourself. This splits a range into 5 equal parts, leaving off the remainder (at most 4 milliseconds):

```js
var n = 5
range.split(range.length() / n, 'ms').slice(0, n)
```
