### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by lionel-bijaoui** [icambron/twix.js#91]
http://isaaccambron.com/ is unavailable and so is the documentation.

http://downforeveryoneorjustme.com/http://isaaccambron.com/

Just in case someone needs it, documentation can be accessed here: https://github.com/icambron/twix.js/blob/master/docs/docs.md

**Comment by icambron** [comment]
Yeah, my DNS host stopped serving my requests after my credit card expired and never bothered to tell me. I'm moving the domain and it should be back up soon.

**Comment by icambron** [comment]
Back up
